// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb2ZbbjG145jXF7vmZ3Mj_CTUzda2aRUk',
    appId: '1:547769029886:web:f4781c741f1e00d7bb41af',
    messagingSenderId: '547769029886',
    projectId: 'foodtracker-dbf2f',
    authDomain: 'foodtracker-dbf2f.firebaseapp.com',
    storageBucket: 'foodtracker-dbf2f.firebasestorage.app',
    measurementId: 'G-4KSZV11LGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc3if2_mCTP5VhDaVyH8sU48VjewH5u3U',
    appId: '1:547769029886:android:39c942c2cfa08fb9bb41af',
    messagingSenderId: '547769029886',
    projectId: 'foodtracker-dbf2f',
    storageBucket: 'foodtracker-dbf2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD989YwyAGi50C_tCK2yQ55IRKhFeA6JyU',
    appId: '1:547769029886:ios:f9a8b60af8112c7fbb41af',
    messagingSenderId: '547769029886',
    projectId: 'foodtracker-dbf2f',
    storageBucket: 'foodtracker-dbf2f.firebasestorage.app',
    iosBundleId: 'com.example.foodDonationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD989YwyAGi50C_tCK2yQ55IRKhFeA6JyU',
    appId: '1:547769029886:ios:f9a8b60af8112c7fbb41af',
    messagingSenderId: '547769029886',
    projectId: 'foodtracker-dbf2f',
    storageBucket: 'foodtracker-dbf2f.firebasestorage.app',
    iosBundleId: 'com.example.foodDonationTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb2ZbbjG145jXF7vmZ3Mj_CTUzda2aRUk',
    appId: '1:547769029886:web:f2fad9e19013f80cbb41af',
    messagingSenderId: '547769029886',
    projectId: 'foodtracker-dbf2f',
    authDomain: 'foodtracker-dbf2f.firebaseapp.com',
    storageBucket: 'foodtracker-dbf2f.firebasestorage.app',
    measurementId: 'G-JE3Z0LHR2Y',
  );
}
